<?php

namespace ContainerQ7dIxPC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JDyeBdXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.jDyeBdX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jDyeBdX'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\CategoryController::delete' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\CategoryController::edit' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\CategoryController::index' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\CategoryController::show' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\ProductController::delete' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController::edit' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController::index' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Controller\\ProductController::new' => ['privates', '.service_locator.1cFtlgg', 'get_ServiceLocator_1cFtlggService', true],
            'App\\Controller\\ProductController::show' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\CategoryController:delete' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\CategoryController:edit' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\CategoryController:index' => ['privates', '.service_locator.zAmj.kw', 'get_ServiceLocator_ZAmj_KwService', true],
            'App\\Controller\\CategoryController:show' => ['privates', '.service_locator.wNIwF8O', 'get_ServiceLocator_WNIwF8OService', true],
            'App\\Controller\\ProductController:delete' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController:edit' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\ProductController:index' => ['privates', '.service_locator.JnHMbEU', 'get_ServiceLocator_JnHMbEUService', true],
            'App\\Controller\\ProductController:new' => ['privates', '.service_locator.1cFtlgg', 'get_ServiceLocator_1cFtlggService', true],
            'App\\Controller\\ProductController:show' => ['privates', '.service_locator.Rc9uH46', 'get_ServiceLocator_Rc9uH46Service', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.xA8Fw_.', 'get_ServiceLocator_XA8Fw_Service', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\CategoryController::delete' => '?',
            'App\\Controller\\CategoryController::edit' => '?',
            'App\\Controller\\CategoryController::index' => '?',
            'App\\Controller\\CategoryController::show' => '?',
            'App\\Controller\\ProductController::delete' => '?',
            'App\\Controller\\ProductController::edit' => '?',
            'App\\Controller\\ProductController::index' => '?',
            'App\\Controller\\ProductController::new' => '?',
            'App\\Controller\\ProductController::show' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\CategoryController:delete' => '?',
            'App\\Controller\\CategoryController:edit' => '?',
            'App\\Controller\\CategoryController:index' => '?',
            'App\\Controller\\CategoryController:show' => '?',
            'App\\Controller\\ProductController:delete' => '?',
            'App\\Controller\\ProductController:edit' => '?',
            'App\\Controller\\ProductController:index' => '?',
            'App\\Controller\\ProductController:new' => '?',
            'App\\Controller\\ProductController:show' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
