<?php

namespace ContainerQ7dIxPC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDemoControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\DemoController' shared autowired service.
     *
     * @return \App\Controller\DemoController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'\\src\\Controller\\DemoController.php';

        return $container->services['App\\Controller\\DemoController'] = new \App\Controller\DemoController(($container->services['twig'] ?? $container->getTwigService()));
    }
}
