<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKKExibk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKKExibk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKKExibk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKKExibk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKKExibk\App_KernelDevDebugContainer([
    'container.build_hash' => 'KKExibk',
    'container.build_id' => '1f6465e7',
    'container.build_time' => 1622447677,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKKExibk');
